### ISSUE TITLE
Im On 1.16.5 and its pulling up an error screen

### ISSUE THREAD

**Issue by GhostWing404** [OreCruncher/DynamicSurroundings2#12]
![2021-02-25 (2)](https://user-images.githubusercontent.com/79675789/109241890-fbe3be00-778e-11eb-8bf6-4d1a5727f27d.png)
ive been trying to open the game for an hour and it keeps coming up with this screen

**Comment by GhostWing404** [comment]
heres my crash report if you need it
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/25/21 5:21 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6693/559900079.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5768/306165867.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:fml:fairylights:GameRendererTransformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.43.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/500985266.call(Unknown Source) [forge-1.16.5-36.0.43.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_51] {re:computing_frames}
-- MOD sndctrl --
Details:
	Mod File: DynamicSurroundings-1.16.4-4.0.1.5.jar
	Failure message: Dynamic Surroundings: Sound Control (sndctrl) encountered an error during the process_imc event phase
		java.lang.IllegalArgumentException: No enum constant org.orecruncher.sndctrl.api.IMC.Methods.enableRendering
	Mod Version: 1.16.4-4.0.1.5
	Mod Issue URL: https://github.com/OreCruncher/DynamicSurroundings2/issues
	Exception message: java.lang.IllegalArgumentException: No enum constant org.orecruncher.sndctrl.api.IMC.Methods.enableRendering
Stacktrace:
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_51] {re:computing_frames}
	at org.orecruncher.sndctrl.api.IMC$Methods.valueOf(IMC.java:176) ~[?:1.16.4-4.0.1.5] {re:classloading}
	at org.orecruncher.sndctrl.api.IMC.lambda$processIMC$0(IMC.java:64) ~[?:1.16.4-4.0.1.5] {re:classloading}
	at org.orecruncher.sndctrl.api.IMC$$Lambda$6625/2136312929.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.InterModComms$QueueFilteringSpliterator.tryAdvance(InterModComms.java:171) ~[?:?] {re:classloading}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at org.orecruncher.sndctrl.api.IMC.processIMC(IMC.java:64) ~[?:1.16.4-4.0.1.5] {re:classloading}
	at org.orecruncher.sndctrl.api.IMC$$Lambda$3825/586853717.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2934/1436538348.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2562/486199082.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3198/1891763647.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1191677296 bytes (1136 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.43.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.43
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.43-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |COMPLETE  |NOSIGNATURE
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |COMPLETE  |NOSIGNATURE
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |COMPLETE  |NOSIGNATURE
		ItemPhysicLite_v1.4.6_mc1.16.2.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |COMPLETE  |NOSIGNATURE
		xray-1.16.4-2.6.0.jar                             |Advanced XRay                 |xray                          |2.6.0               |COMPLETE  |NOSIGNATURE
		practicaltools-1.16.3-1.8.jar                     |Practical Tools               |practicaltools                |1.16.3-1.8          |COMPLETE  |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |COMPLETE  |NOSIGNATURE
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                |COMPLETE  |NOSIGNATURE
		FallingTree-Forge-1.16.4-2.7.0.jar                |Falling Tree                  |falling_tree                  |2.7.0               |COMPLETE  |NOSIGNATURE
		fishtraps-0.1.2.jar                               |Fish Traps                    |fishtraps                     |1.16.3-0.1.2        |COMPLETE  |NOSIGNATURE
		fairylights-4.0.4-1.16.4.jar                      |Fairy Lights                  |fairylights                   |4.0.4               |COMPLETE  |NOSIGNATURE
		callablehorses-1.16.3-1.2.1.4.jar                 |Callable Horses               |callablehorses                |1.2.1.4             |COMPLETE  |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		PerspectiveModRedux-forge-1.16.2-0.0.5.jar        |Perspective Mod Redux         |pmr                           |0.0.5               |COMPLETE  |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |COMPLETE  |NOSIGNATURE
		create-mc1.16.3_v0.3c.jar                         |Create                        |create                        |mc1.16.3_v0.3c      |COMPLETE  |NOSIGNATURE
		Xaeros_Minimap_21.2.0.2_Forge_1.16.5.jar          |Xaero's Minimap               |xaerominimap                  |21.2.0              |COMPLETE  |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |COMPLETE  |NOSIGNATURE
		TerraForged-1.16.4-0.2.8.jar                      |TerraForged                   |terraforged                   |0.2.8               |COMPLETE  |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		backslot-1.16.3-1.2.0.0.jar                       |�cBack �9Slot                 |backslot                      |1.16.3-1.2.0.0      |COMPLETE  |NOSIGNATURE
		extlights-3.3.jar                                 |Extended Lights               |extlights                     |3.3                 |COMPLETE  |NOSIGNATURE
		fakeblocks-1.16.4-1.0.1.jar                       |Fake Blocks                   |fakeblocks                    |1.16.4-1.0.1        |COMPLETE  |NOSIGNATURE
		TravelersBackpack-1.16.4-5.3.8.jar                |Traveler's Backpack           |travelersbackpack             |5.3.8               |COMPLETE  |NOSIGNATURE
		elevatorid-1.16.4-1.7.8.jar                       |Elevator Mod                  |elevatorid                    |1.16.4-1.7.8        |COMPLETE  |NOSIGNATURE
		decorative_blocks-1.16.4-1.6.0.jar                |Decorative Blocks             |decorative_blocks             |1.6.0               |COMPLETE  |NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.2.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.2.1               |COMPLETE  |NOSIGNATURE
		buildersaddition-1.16.4-20201203a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.4-20201203a    |COMPLETE  |NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.0-dist.jar           |WorldEdit                     |worldedit                     |7.2.0+a51fa43       |COMPLETE  |NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |COMPLETE  |NOSIGNATURE
		additional_lights-1.16.4-2.1.3 - Copy.jar         |Additional Lights             |additional_lights             |2.1.3               |COMPLETE  |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |COMPLETE  |NOSIGNATURE
		cloth-config-4.11.14-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.14             |COMPLETE  |NOSIGNATURE
		immersive-portals-0.14-mc1.16.4-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |COMPLETE  |NOSIGNATURE
		panorama-1.1.jar                                  |Panorama                      |panorama                      |1.0.0               |COMPLETE  |NOSIGNATURE
		forge-1.16.5-36.0.43-universal.jar                |Forge                         |forge                         |36.0.43             |COMPLETE  |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		moveplus-1.16.4-2.5.1.jar                         |Move Plus                     |moveplus                      |1.16.4-2.5.1        |COMPLETE  |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMPLETE  |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.1.5.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.1.5      |COMPLETE  |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
	Crash Report UUID: c51256e3-d12e-4a89-bac1-67be4486ee8c

**Comment by OreCruncher** [comment]
Make sure you are using the latest Dynamic Surroundings (4.0.6.11).

**Comment by GhostWing404** [comment]
okay now i have a new problem i changed the version of dynamic surroundings im using the most recent one but now it wont work with optifine witch is reallllly bad because my pc will quite literally BURN without optifine on why is it doing this?

**Comment by GhostWing404** [comment]
nvm it was immersive portals lol
